name: Android CI

on: workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run unit tests
      run: ./gradlew test --stacktrace

    - name: Decode Keystore
      env:
        STORE_FILE: ${{ secrets.STORE_FILE }}
      run: echo $STORE_FILE | base64 -di > keystore

      
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
      env:
        STORE_FILE: ../keystore
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Build artifacts
        path: app/build/outputs

